config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :answers do
    get 'mark_best', as: "mark_best"
    get 'score_plus', as: "score_plus"
    get 'score_minus', as: "score_minus"
  end

  resources :questions do
    get 'score_plus', as: "score_plus"
    get 'score_minus', as: "score_minus"
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :users

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments

  validates :content, presence: true

  accepts_nested_attributes_for :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  belongs_to :answer

  validates :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :answers

  validates :content, presence: true

  paginates_per 20

  accepts_nested_attributes_for :answers
  accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :comments
  has_many :answers


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_answer_in_question, only: [:mark_best, :score_plus, :score_minus]
  before_action :authenticate_user!
  
  respond_to :html

  def index
    @answers = Answer.all
    respond_with(@answers)
  end

  def show
    respond_with(@answer)
  end

  def new
    @answer = Answer.new
    respond_with(@answer)
  end

  def edit
  end

  def mark_best
    @question = Question.find(@answer.question_id)
    @question.answers.each do |a|
      a.update_attributes(:best_answer => nil)
    end
    @answer.update_attributes(:best_answer => true)
    redirect_to question_path(@answer.question.id)
  end

  def score_plus
    if @answer.score.nil?
      new_score = 1 
    else
      new_score = @answer.score + 1 
    end
    @answer.update_attributes(:score => new_score)
    redirect_to question_path(@answer.question.id)
  end

  def score_minus
    if @answer.score.nil? || @answer.score == 0
      new_score = 0 
    else
      new_score = @answer.score - 1 
    end
    @answer.update_attributes(:score => new_score)
    redirect_to question_path(@answer.question.id)
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.save
    redirect_to question_path(@answer.question.id)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    @answer.destroy
    respond_with(@answer)
  end

  private
    def set_answer_in_question
      @answer = Answer.find(params[:answer_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:user_id, :question_id, :content, :score, :best_answer, comments_attributes: [:user_id, :content])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to question_path(@comment.question.id)
    # respond_with(@comment)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :question_id, :answer_id, :content)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_question_score, only: [:score_plus, :score_minus]
  before_action :authenticate_user!

  respond_to :html

  def index
    @questions = Question.order("created_at desc").page params[:page]
    respond_with(@questions)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def score_plus
    if @question.score.nil?
      new_score = 1 
    else
      new_score = @question.score + 1 
    end
    @question.update_attributes(:score => new_score)
    redirect_to question_path(@question.id)
  end

  def score_minus
    if @question.score.nil? || @question.score == 0
      new_score = 0 
    else
      new_score = @question.score - 1 
    end
    @question.update_attributes(:score => new_score)
    redirect_to question_path(@question.id)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @question.save
    respond_with(@question)
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private
    def set_question_score
      @question = Question.find(params[:question_id])
    end
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:content, :score, :user_id, answers_attributes: [:user_id, :content], comments_attributes: [:user_id, :content])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @questions = @user.questions.order("created_at desc").limit(5)
    @answers = @user.answers.order("created_at desc").limit(5)
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :firstname, :lastname)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :best_answer %><br>
    <%= f.check_box :best_answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Content</th>
      <th>Score</th>
      <th>Best answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.content %></td>
        <td><%= answer.score %></td>
        <td><%= answer.best_answer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Score:</strong>
  <%= @answer.score %>
</p>

<p>
  <strong>Best answer:</strong>
  <%= @answer.best_answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.question_id %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @comment.question_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExamCenturan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Profile", user_path(current_user) %>  |
<%= link_to "Questions", questions_path %>  |
<%= link_to "Logout", destroy_user_session_path, :method => :delete %>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Score</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.score %></td>
        <td><%= question.user_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @questions %>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Score:</strong>
  <%= @question.score %>
</p>
<p>
  <%= link_to "<button>+</button>".html_safe, question_score_plus_path(@question.id) %>
  <%= link_to "<button>-</button>".html_safe, question_score_minus_path(@question.id) %>
</p>
<p>
  <strong>User:</strong>
  <%= @question.user_id %>
</p>
<p><strong>Answers:</strong></p>
<%- @question.answers.each do |a| %>

  <%- if current_user.id == @question.user_id %>
    <p><%= a.content %>
      <%= link_to "<button>+</button>".html_safe, answer_score_plus_path(a.id) %>
      <%= link_to "<button>-</button>".html_safe, answer_score_minus_path(a.id) %>
      <%= a.best_answer %>
      <% if a.best_answer %>
        <b>IS THE BEST</b>
      <% elsif a.best_answer.nil? %>
        <%= link_to "<button>BEST</button>".html_safe, answer_mark_best_path(a.id) %>
      <% end -%>
      <strong>score: <%= a.score %></strong>
    </p>
  <% else %>
    <p><%= a.content %>
      <%= link_to "<button>+</button>".html_safe, answer_score_plus_path(a.id) %>
      <%= link_to "<button>-</button>".html_safe, answer_score_minus_path(a.id) %>
      <% if a.best_answer %>
        <b>IS THE BEST</b>
      <% end -%>
      <strong>score: <%= a.score %></strong>
    </p>
  <% end -%>
  <p style="padding-left: 15px"><strong>Comments</strong></p>
  <% a.comments.each do |c| %>
    <p style="padding-left: 15px"><%= c.content %></p>
  <% end -%>
  <%= form_for Comment.new do |comment| %>
    <%= comment.text_field :content %>
    <%= comment.hidden_field :user_id, value: current_user.id %>
    <%= comment.hidden_field :question_id, value: @question.id %>
    <%= comment.hidden_field :answer_id, value: a.id %>
    <%= comment.submit %>
  <% end -%>
<% end -%>
<%= form_for Answer.new do |answer| %>
  <%= answer.text_field :content %>
  <%= answer.hidden_field :user_id, value: current_user.id %>
  <%= answer.hidden_field :question_id, value: @question.id %>
  <%= answer.submit %>
<% end -%>

<p><strong>Comments:</strong></p>
<%- @question.comments.each do |a| %>
  <p><%= a.content %></p>
<% end -%>
<%= form_for Comment.new do |comment| %>
  <%= comment.text_field :content %>
  <%= comment.hidden_field :user_id, value: current_user.id %>
  <%= comment.hidden_field :question_id, value: @question.id %>
  <%= comment.submit %>
<% end -%>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>
<h3>question: </h3>
<%- @questions.each do |question| %>
  <p><%= link_to question.content, question_path(question) %></p>
<% end -%>
<h3>answers: </h3>
<%- @answers.each do |answer| %>
  <p><%= link_to answer.content, answer_path(answer) %></p>
<% end -%>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>